"""previews

Revision ID: 059ed671e358
Revises: 58eb42ecad11
Create Date: 2020-11-25 15:57:57.162403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '059ed671e358'
down_revision = '58eb42ecad11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pv_filter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('channel_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('channel_id')
    )
    op.create_table('pv_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pv_settings')
    op.drop_table('pv_filter')
    # ### end Alembic commands ###
