"""dbguild delete_at column

Revision ID: 58eb42ecad11
Revises: 709659dbc64e
Create Date: 2020-11-25 13:15:13.661339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58eb42ecad11'
down_revision = '709659dbc64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('guilds', sa.Column('delete_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('guilds', 'delete_at')
    # ### end Alembic commands ###
