"""0.2.0 init

Revision ID: 709659dbc64e
Revises: 
Create Date: 2020-11-23 21:56:27.037601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709659dbc64e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_prefix', sa.Text(), nullable=False),
    sa.Column('verbose_errors', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('guilds',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bu_events',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.UUID(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_channel', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('banner_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=True),
    sa.Column('unbanned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('command_prefix', sa.Text(), nullable=True),
    sa.Column('verbose_errors', sa.Boolean(), nullable=True),
    sa.Column('authenticated_role', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ww_ignores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('mention_type', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ww_ignores_target_id'), 'ww_ignores', ['target_id'], unique=False)
    op.create_table('ww_ping_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ww_ping_groups_name'), 'ww_ping_groups', ['name'], unique=False)
    op.create_table('ww_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.Column('header', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ww_pings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ping_type', sa.String(length=2), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('group', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group'], ['ww_ping_groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ww_watches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guild', sa.BigInteger(), nullable=True),
    sa.Column('pattern', sa.Text(), nullable=False),
    sa.Column('match_type', sa.Integer(), nullable=False),
    sa.Column('ping_group', sa.Integer(), nullable=True),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.Column('ignore_case', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['guild'], ['guilds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ping_group'], ['ww_ping_groups.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ww_watches_pattern'), 'ww_watches', ['pattern'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ww_watches_pattern'), table_name='ww_watches')
    op.drop_table('ww_watches')
    op.drop_table('ww_pings')
    op.drop_table('ww_settings')
    op.drop_index(op.f('ix_ww_ping_groups_name'), table_name='ww_ping_groups')
    op.drop_table('ww_ping_groups')
    op.drop_index(op.f('ix_ww_ignores_target_id'), table_name='ww_ignores')
    op.drop_table('ww_ignores')
    op.drop_table('settings')
    op.drop_table('bu_events')
    op.drop_table('guilds')
    op.drop_table('global_settings')
    # ### end Alembic commands ###
