"""initial

Revision ID: db2af4d915b6
Revises: 
Create Date: 2020-11-17 17:56:52.184489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db2af4d915b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_events',
    sa.Column('id', ormar.fields.sqlalchemy_uuid.UUID(), nullable=False),
    sa.Column('guild_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=False),
    sa.Column('message_channel', sa.BigInteger(), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=False),
    sa.Column('banner_id', sa.BigInteger(), nullable=True),
    sa.Column('ban_reason', sa.Text(), nullable=False),
    sa.Column('reported', sa.Boolean(), nullable=True),
    sa.Column('unbanned', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_ban_events_guild_id'), 'ban_events', ['guild_id'], unique=False)
    op.create_table('global_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_prefix', sa.Text(), nullable=False),
    sa.Column('verbose_errors', sa.Boolean(), nullable=False),
    sa.Column('secret_key', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('settings',
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('enabled_modules', sa.Integer(), nullable=True),
    sa.Column('command_prefix', sa.Text(), nullable=True),
    sa.Column('verbose_errors', sa.Boolean(), nullable=True),
    sa.Column('authenticated_role', sa.BigInteger(), nullable=True),
    sa.Column('log_channel', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('server_id'),
    sa.UniqueConstraint('server_id')
    )
    op.create_table('sus_words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('server_id', sa.BigInteger(), nullable=False),
    sa.Column('regex', sa.Text(), nullable=False),
    sa.Column('auto_delete', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sus_words_server_id'), 'sus_words', ['server_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sus_words_server_id'), table_name='sus_words')
    op.drop_table('sus_words')
    op.drop_table('settings')
    op.drop_table('global_settings')
    op.drop_index(op.f('ix_ban_events_guild_id'), table_name='ban_events')
    op.drop_table('ban_events')
    # ### end Alembic commands ###
